--------------------------------------------------------
-- Archivo creado  - viernes-febrero-04-2022   
--------------------------------------------------------
DROP TABLE "PROYECTO"."DATOS_USUARIOS" cascade constraints;
DROP TABLE "PROYECTO"."USUARIOS" cascade constraints;
DROP TABLE "PROYECTO"."USUARIOS" cascade constraints;
DROP TABLE "PROYECTO"."DATOS_USUARIOS" cascade constraints;
--------------------------------------------------------
--  DDL for Table DATOS_USUARIOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."DATOS_USUARIOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"APELLIDOS" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(15 BYTE), 
	"TLF" VARCHAR2(11 BYTE), 
	"DIRECCION" VARCHAR2(20 BYTE), 
	"CIUDAD" VARCHAR2(10 BYTE), 
	"CODIGOPOSTAL" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."USUARIOS" 
   (	"USUARIO" VARCHAR2(9 BYTE), 
	"CONTRASEÑA" VARCHAR2(128 BYTE), 
	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."USUARIOS" 
   (	"USUARIO" VARCHAR2(9 BYTE), 
	"CONTRASEÑA" VARCHAR2(128 BYTE), 
	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DATOS_USUARIOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."DATOS_USUARIOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"APELLIDOS" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(15 BYTE), 
	"TLF" VARCHAR2(11 BYTE), 
	"DIRECCION" VARCHAR2(20 BYTE), 
	"CIUDAD" VARCHAR2(10 BYTE), 
	"CODIGOPOSTAL" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PROYECTO.DATOS_USUARIOS
SET DEFINE OFF;
REM INSERTING into PROYECTO.USUARIOS
SET DEFINE OFF;
Insert into PROYECTO.USUARIOS (USUARIO,"CONTRASEÑA",ID) values ('aaaaaaaa','3d84b86704694789004bbc7a082b8c3f9adb652ff54ac409f08e65c39300ea8328925da77c4622e48ed743b546db7f823f5ce3508a2539a460d327cc75fb42d8','1');
Insert into PROYECTO.USUARIOS (USUARIO,"CONTRASEÑA",ID) values ('1234','5d0ca2f5cfe017db3d0f04ab90d8a30b99302e79c2a05054e67cb462f9738c05025c4538fb610da7e4a457be50a18255248bdcf9866116c41f2fe9c246f23e19','2');
--------------------------------------------------------
--  DDL for Index SYS_C007248
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."SYS_C007248" ON "PROYECTO"."DATOS_USUARIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007247
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."SYS_C007247" ON "PROYECTO"."USUARIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DATOS_USUARIOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DATOS_USUARIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."USUARIOS" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."USUARIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DATOS_USUARIOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DATOS_USUARIOS" ADD CONSTRAINT "FK_ID" FOREIGN KEY ("ID")
	  REFERENCES "PROYECTO"."USUARIOS" ("ID") ENABLE;
